version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: valery_db
    restart: always
    environment:
      POSTGRES_USER: valery_user
      POSTGRES_PASSWORD: valery_password
      POSTGRES_DB: valery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
